routes/web.php
<?php

use App\Http\Controllers\ClientController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\StockController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [AboutController::class, 'index'])->name('about');
Route::resource('client', ClientController::class)->only(['index', 'show']);
Route::resource('stock', StockController::class)->only(['index']);

resources/views/page/about.blade.php
@extends('layout.layout')

@section('content')
<main class="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
    <div class="sm:text-center lg:text-left">
        <h1 class="text-4xl tracking-tight font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
            <span class="block xl:inline">Fantasy</span>
            <span class="block text-indigo-600 xl:inline">Finance</span>
        </h1>

        <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">
            You are the CEO of a major financial institution. Your goal is to make as much money as
            possible while avoiding regulation and bad publicity. You will use a variety of financial
            instruments to make deals and grow your empire. But be careful, because if you get too
            greedy you may find yourself in hot water.
        </p>
        <p class="mt-1 text-sm text-gray-300">
            Description generated by openAI 😅
        </p>
        <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">
            You can start over anytime. It will rollup database from scratch and seed test data.
        </p>
        <div class="mt-5 sm:mt-8 sm:flex sm:justify-center lg:justify-start">
            <div class="mt-3 sm:mt-0 sm:ml-3">
                <a href="{{ route('client.index') }}"
                   class="w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 md:py-4 md:text-lg md:px-10">
                    Get started
                </a>
            </div>
            <livewire:start-over />
        </div>
    </div>
</main>
@stop

@section('sidebar')
    <div class="lg:absolute lg:inset-y-0 lg:right-0 lg:w-1/2">
        <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
        <lottie-player src="https://assets5.lottiefiles.com/packages/lf20_z6scuqaw.json"
                       background="#E0E8FF"
                       speed="1" style="width: 620px; height: 620px;" loop autoplay></lottie-player>
    </div>
@stop